/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Utilidades.ConfigTelas;
import Utilidades.ConnectionFactory;
import com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Cidade;
import model.Cliente;
import model.Estado;
import model.OrdemServico;
import model.SituacaoCliente;

/**
 *
 * @author Produção
 */
public class TelaCadastroCliente extends javax.swing.JFrame {

    Cliente c = new Cliente();
    private boolean validado = true;
    private boolean testeOS = false;

    /**
     * Creates new form CadastroCliente
     */
    public TelaCadastroCliente() {
        initComponents();
        ConfigTelas ct = new ConfigTelas(this);
        ct.carregarConfig(this);
        jComboBox1.setVisible(false);

    }

    public TelaCadastroCliente(boolean teste) {
        this.testeOS = teste;
        initComponents();
        ConfigTelas ct = new ConfigTelas(this);
        ct.carregarConfig(this);
        this.habilitaNovo();
        jComboBox1.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        SistotalPUEntityManager = ConnectionFactory.getEntityManager();
        clienteQuery = java.beans.Beans.isDesignTime() ? null : SistotalPUEntityManager.createQuery("SELECT c FROM Cliente c");
        clienteList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(clienteQuery.getResultList());
        estadoQuery = java.beans.Beans.isDesignTime() ? null : SistotalPUEntityManager.createQuery("SELECT e FROM Estado e");
        estadoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(estadoQuery.getResultList());
        cidadeQuery = java.beans.Beans.isDesignTime() ? null : SistotalPUEntityManager.createQuery("SELECT c FROM Cidade c");
        cidadeList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(cidadeQuery.getResultList());
        situacaoClienteQuery = java.beans.Beans.isDesignTime() ? null : SistotalPUEntityManager.createQuery("SELECT s FROM SituacaoCliente s");
        situacaoClienteList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : situacaoClienteQuery.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldRua = new javax.swing.JTextField();
        jTextFieldComplemento = new javax.swing.JTextField();
        jTextFieldBairro = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jComboBoxEstado = new javax.swing.JComboBox();
        jComboBoxCidade = new javax.swing.JComboBox();
        jTextFieldCPF = new javax.swing.JTextField();
        jTextFieldInscricaoEstadual = new javax.swing.JTextField();
        jComboBoxSituacao = new javax.swing.JComboBox();
        jTextFieldFone = new javax.swing.JTextField();
        jTextFieldCelular = new javax.swing.JTextField();
        jButtonGravar = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldCep = new javax.swing.JTextField();
        jTextFieldNr = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButtonExcluir = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButtonSair = new javax.swing.JButton();
        jTextFieldFiltro = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButtonOS = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldInscricaoMunicipal = new javax.swing.JTextField();
        jButtonEditar = new javax.swing.JButton();
        jButtonListaOS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(766, 654));
        jPanel1.setLayout(null);

        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, clienteList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idcliente}"));
        columnBinding.setColumnName("Codigo");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fone}"));
        columnBinding.setColumnName("Fone");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${celular}"));
        columnBinding.setColumnName("Celular");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${email}"));
        columnBinding.setColumnName("Email");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cpfCnpj}"));
        columnBinding.setColumnName("Cpf Cnpj");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idsituacaoCliente.descricao}"));
        columnBinding.setColumnName("Situação");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(50);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(1).setMinWidth(180);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(180);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(180);
            jTable1.getColumnModel().getColumn(2).setMinWidth(110);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(110);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(110);
            jTable1.getColumnModel().getColumn(3).setMinWidth(110);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(110);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(110);
            jTable1.getColumnModel().getColumn(5).setMinWidth(100);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(6).setMinWidth(60);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(6).setMaxWidth(60);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 75, 880, 273);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Nome:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 360, 200, 20);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Rua:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(470, 360, 190, 20);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Nr:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(680, 360, 50, 20);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Complemento:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 410, 160, 20);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Bairro:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(190, 410, 60, 20);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("e-mail:");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(290, 360, 170, 20);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Estado:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 460, 60, 20);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Cidade:");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(170, 460, 80, 20);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("CPF/CNPJ:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(320, 460, 80, 20);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Insc Estadual:");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(460, 460, 100, 20);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Data Cadastro:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(750, 460, 90, 20);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Fone:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(630, 410, 50, 20);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Celular:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(470, 410, 60, 20);

        jTextFieldNome.setEditable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nome}"), jTextFieldNome, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jTextFieldNome);
        jTextFieldNome.setBounds(80, 380, 200, 25);

        jTextFieldRua.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.endereco}"), jTextFieldRua, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jTextFieldRua);
        jTextFieldRua.setBounds(470, 380, 190, 25);

        jTextFieldComplemento.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.complemento}"), jTextFieldComplemento, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jTextFieldComplemento);
        jTextFieldComplemento.setBounds(20, 430, 160, 25);

        jTextFieldBairro.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.bairro}"), jTextFieldBairro, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jTextFieldBairro);
        jTextFieldBairro.setBounds(190, 430, 130, 25);

        jTextFieldEmail.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.email}"), jTextFieldEmail, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(290, 380, 170, 25);

        jComboBoxEstado.setEnabled(false);

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, estadoList, jComboBoxEstado, "");
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.idcidade.idestado}"), jComboBoxEstado, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jComboBoxEstado);
        jComboBoxEstado.setBounds(20, 480, 130, 25);

        jComboBoxCidade.setEnabled(false);

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, cidadeList, jComboBoxCidade);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.idcidade}"), jComboBoxCidade, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jComboBoxCidade);
        jComboBoxCidade.setBounds(170, 480, 130, 25);

        jTextFieldCPF.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.cpfCnpj}"), jTextFieldCPF, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextFieldCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPFActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCPF);
        jTextFieldCPF.setBounds(320, 480, 130, 25);

        jTextFieldInscricaoEstadual.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.inscEstadual}"), jTextFieldInscricaoEstadual, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jTextFieldInscricaoEstadual);
        jTextFieldInscricaoEstadual.setBounds(460, 480, 130, 25);

        jComboBoxSituacao.setEnabled(false);

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, situacaoClienteList, jComboBoxSituacao);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.idsituacaoCliente}"), jComboBoxSituacao, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jComboBoxSituacao);
        jComboBoxSituacao.setBounds(770, 430, 130, 25);

        jTextFieldFone.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.fone}"), jTextFieldFone, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jTextFieldFone);
        jTextFieldFone.setBounds(620, 430, 130, 25);

        jTextFieldCelular.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.celular}"), jTextFieldCelular, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextFieldCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCelularActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCelular);
        jTextFieldCelular.setBounds(470, 430, 130, 25);

        jButtonGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/32x32/gravar32.png"))); // NOI18N
        jButtonGravar.setText("Gravar");
        jButtonGravar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGravar.setMaximumSize(new java.awt.Dimension(65, 65));
        jButtonGravar.setMinimumSize(new java.awt.Dimension(65, 65));
        jButtonGravar.setPreferredSize(new java.awt.Dimension(65, 65));
        jButtonGravar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jButtonGravar, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGravar);
        jButtonGravar.setBounds(460, 530, 90, 80);

        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/32x32/add_user.png"))); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNovo.setPreferredSize(new java.awt.Dimension(65, 65));
        jButtonNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNovo);
        jButtonNovo.setBounds(240, 530, 90, 80);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("CEP:");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel14);
        jLabel14.setBounds(330, 410, 50, 20);

        jTextFieldCep.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.cep}"), jTextFieldCep, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jTextFieldCep);
        jTextFieldCep.setBounds(330, 430, 130, 25);

        jTextFieldNr.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.numero}"), jTextFieldNr, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jTextFieldNr);
        jTextFieldNr.setBounds(680, 380, 70, 25);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Codigo:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(20, 360, 50, 20);

        jTextField1.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.idcliente}"), jTextField1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jTextField1);
        jTextField1.setBounds(20, 380, 50, 25);

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, clienteList, jComboBox1);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement}"), jComboBox1, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(20, 620, 130, 20);

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/32x32/delete_user.png"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonExcluir.setPreferredSize(new java.awt.Dimension(65, 65));
        jButtonExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jButtonExcluir, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExcluir);
        jButtonExcluir.setBounds(130, 530, 90, 80);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Situação:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(770, 410, 70, 20);

        jFormattedTextField1.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.dataCadastro}"), jFormattedTextField1, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jFormattedTextField1);
        jFormattedTextField1.setBounds(750, 480, 130, 25);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/32x32/sair2.png"))); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSair);
        jButtonSair.setBounds(800, 530, 90, 80);

        jTextFieldFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFiltroKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldFiltro);
        jTextFieldFiltro.setBounds(10, 40, 340, 25);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Cadastro de Clientes");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(0, 10, 910, 30);

        jButtonOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/32x32/nova_os.png"))); // NOI18N
        jButtonOS.setText("Nova OS");
        jButtonOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonOS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jButtonOS, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jButtonOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOSActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOS);
        jButtonOS.setBounds(350, 530, 90, 80);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Insc Municipal:");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel18);
        jLabel18.setBounds(610, 460, 100, 20);

        jTextFieldInscricaoMunicipal.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.inscMunicipal}"), jTextFieldInscricaoMunicipal, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jTextFieldInscricaoMunicipal);
        jTextFieldInscricaoMunicipal.setBounds(610, 480, 130, 25);

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/32x32/edit_profile.png"))); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEditar.setPreferredSize(new java.awt.Dimension(65, 65));
        jButtonEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jButtonEditar, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditar);
        jButtonEditar.setBounds(20, 530, 90, 80);

        jButtonListaOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/32x32/10693_32x32.png"))); // NOI18N
        jButtonListaOS.setText("Lista OS");
        jButtonListaOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonListaOS.setPreferredSize(new java.awt.Dimension(65, 65));
        jButtonListaOS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jButtonListaOS, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jButtonListaOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListaOSActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonListaOS);
        jButtonListaOS.setBounds(570, 530, 90, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        setSize(new java.awt.Dimension(922, 692));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPFActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        Cliente c = new Cliente();
        new TelaDetalharCliente(this, true, c, true, false).setVisible(true);
        
//        habilitaNovo();
//        liberaEdicao();
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void habilitaNovo() {
        SistotalPUEntityManager.persist(this.c);
        clienteList.add(this.c);
        int row = clienteList.size() - 1;
        jTable1.setRowSelectionInterval(row, row);
        jTable1.scrollRectToVisible(jTable1.getCellRect(row, 0, true));
        jTextFieldNome.requestFocus();
        //Dados padrão
        jComboBoxEstado.setSelectedItem(new Estado(21));
        jComboBoxCidade.setSelectedItem(new Cidade(4266));
        jComboBoxSituacao.setSelectedItem(new SituacaoCliente(1));

    }

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed
        int linhaSelecionada = jTable1.getSelectedRow();

        //validado = Validadores.verificaNr(jTextFieldNr.getText());
        if (validado) {
            if (jTable1.getModel().getValueAt(linhaSelecionada, 0) == null) {
                c.setNome(jTextFieldNome.getText());
                c.setEndereco(jTextFieldRua.getText());
                c.setNumero(jTextFieldNr.getText());
                c.setComplemento(jTextFieldComplemento.getText());
                c.setBairro(jTextFieldBairro.getText());
                c.setCep(jTextFieldCep.getText());
                c.setEmail(jTextFieldEmail.getText());
                c.setIdcidade((Cidade) jComboBoxCidade.getSelectedItem());
                c.setCpfCnpj(jTextFieldCPF.getText());
                c.setInscEstadual(jTextFieldInscricaoEstadual.getText());
                c.setIdsituacaoCliente((SituacaoCliente) jComboBoxSituacao.getSelectedItem());
                c.setCelular(jTextFieldCelular.getText());
                c.setFone(jTextFieldFone.getText());
                c.setDataCadastro(new Date(System.currentTimeMillis()));
                SistotalPUEntityManager.getTransaction().begin();
                SistotalPUEntityManager.persist(this.c);
                SistotalPUEntityManager.getTransaction().commit();
                JOptionPane.showMessageDialog(rootPane, "Dados gravados com sucesso");

            } else {
                SistotalPUEntityManager.getTransaction().begin();
                //SistotalPUEntityManager.persist(this.c);
                SistotalPUEntityManager.getTransaction().commit();
                JOptionPane.showMessageDialog(rootPane, "Dados gravados com sucesso");
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Verifique os campos");
        }

        if (this.testeOS == true) {
            TelaCadastroOrdemServico tosc = new TelaCadastroOrdemServico(c);
            tosc.setVisible(true);
            this.dispose();

        } else {
            atualizaTela();
            bloqueiaEdicao();
        }

    }//GEN-LAST:event_jButtonGravarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
//        int valor = JOptionPane.showConfirmDialog(rootPane, "Você tem certeza que deseja excluir?");
//        if (valor == 0) {
//            Cliente c = (Cliente) jComboBox1.getSelectedItem();
//            try {
//                SistotalPUEntityManager.getTransaction().begin();
//                SistotalPUEntityManager.remove(c);
//                SistotalPUEntityManager.getTransaction().commit();
//            } catch (    MySQLIntegrityConstraintViolationException | javax.persistence.RollbackException | org.eclipse.persistence.exceptions.DatabaseException ex) {
//                Logger.getLogger(TelaCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
//            }
//
//
//
//
//        }
//        atualizaTela();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void excluirCliente(Cliente c) throws MySQLIntegrityConstraintViolationException {

        SistotalPUEntityManager.getTransaction().begin();
        SistotalPUEntityManager.remove(c);
        SistotalPUEntityManager.getTransaction().commit();

    }
    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jTextFieldCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCelularActionPerformed

    private void jTextFieldFiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFiltroKeyTyped
        String filtro = jTextFieldFiltro.getText();
        clienteQuery = SistotalPUEntityManager.createNativeQuery("Select * from cliente where nome like '%" + filtro + "%'", Cliente.class);
        clienteList.clear();
        clienteList.addAll(clienteQuery.getResultList());
    }//GEN-LAST:event_jTextFieldFiltroKeyTyped

    private void jButtonOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOSActionPerformed
        Cliente c = new Cliente();
        c = (Cliente) jComboBox1.getSelectedItem();
        TelaCadastroOrdemServico tosc = new TelaCadastroOrdemServico(c);
        tosc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonOSActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        //this.liberaEdicao();
        Cliente c = new Cliente();
        c = (Cliente) jComboBox1.getSelectedItem();
        TelaDetalharCliente tdc = new TelaDetalharCliente(this, true, c, false, true);
        tdc.setVisible(true);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonListaOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListaOSActionPerformed
        Cliente c = new Cliente();
        c = (Cliente) jComboBox1.getSelectedItem();
        new TelaListaOsPorCliente(this, true, c).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButtonListaOSActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() > 1) {
            Cliente c = new Cliente();
            c = (Cliente) jComboBox1.getSelectedItem();
            new TelaListaOsPorCliente(this, true, c).setVisible(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void liberaEdicao() {
        jTextFieldBairro.setEditable(true);
        jTextFieldCPF.setEditable(true);
        jTextFieldCelular.setEditable(true);
        jTextFieldCep.setEditable(true);
        jTextFieldComplemento.setEditable(true);
        jTextFieldEmail.setEditable(true);
        jTextFieldFone.setEditable(true);
        jTextFieldInscricaoEstadual.setEditable(true);
        jTextFieldNome.setEditable(true);
        jTextFieldNr.setEditable(true);
        jTextFieldRua.setEditable(true);
    }

    private void bloqueiaEdicao() {
        jTextFieldBairro.setEditable(false);
        jTextFieldCPF.setEditable(false);
        jTextFieldCelular.setEditable(false);
        jTextFieldCep.setEditable(false);
        jTextFieldComplemento.setEditable(false);
        jTextFieldEmail.setEditable(false);
        jTextFieldFone.setEditable(false);
        jTextFieldInscricaoEstadual.setEditable(false);
        jTextFieldNome.setEditable(false);
        jTextFieldNr.setEditable(false);
        jTextFieldRua.setEditable(false);
    }

    private void limpaCampos() {
        jTextFieldBairro.setText("");
        jTextFieldCPF.setText("");
        jTextFieldCelular.setText("");
        jTextFieldCep.setText("");
        jTextFieldComplemento.setText("");
        jTextFieldEmail.setText("");
        jTextFieldFone.setText("");
        jTextFieldInscricaoEstadual.setText("");
        jTextFieldNome.setText("");
        jTextFieldNr.setText("");
        jTextFieldRua.setText("");

    }

    private void atualizaTela() {
        //SistotalPUEntityManager.getTransaction().rollback();
        //SistotalPUEntityManager.getTransaction().begin();
        java.util.Collection data = clienteQuery.getResultList();
        for (Object entity : data) {
            SistotalPUEntityManager.refresh(entity);
        }
        clienteQuery = SistotalPUEntityManager.createQuery("SELECT c FROM Cliente c");
        clienteList.clear();
        clienteList.addAll(clienteQuery.getResultList());
        limpaCampos();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                System.out.println(info.getName());
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    //break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaCadastroCliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager SistotalPUEntityManager;
    private java.util.List<model.Cidade> cidadeList;
    private javax.persistence.Query cidadeQuery;
    private java.util.List<model.Cliente> clienteList;
    private javax.persistence.Query clienteQuery;
    private java.util.List<model.Estado> estadoList;
    private javax.persistence.Query estadoQuery;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JButton jButtonListaOS;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonOS;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBoxCidade;
    private javax.swing.JComboBox jComboBoxEstado;
    private javax.swing.JComboBox jComboBoxSituacao;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldCelular;
    private javax.swing.JTextField jTextFieldCep;
    private javax.swing.JTextField jTextFieldComplemento;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFiltro;
    private javax.swing.JTextField jTextFieldFone;
    private javax.swing.JTextField jTextFieldInscricaoEstadual;
    private javax.swing.JTextField jTextFieldInscricaoMunicipal;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNr;
    private javax.swing.JTextField jTextFieldRua;
    private java.util.List<model.SituacaoCliente> situacaoClienteList;
    private javax.persistence.Query situacaoClienteQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
