/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Utilidades.ConfigTelas;
import Utilidades.ConnectionFactory;
import controller.OrdemServicoController;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.OrdemServico;
import relatorios.ExecutaRelatorio;

/**
 *
 * @author Produção
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        ConfigTelas ct = new ConfigTelas(this);
        ct.carregarConfig(this);
        inicializarParametrosTela();

    }

    private void inicializarParametrosTela() {
        jComboBoxOsSelecionada.setVisible(false);
        jComboBoxSituacaoOs.setVisible(false);
        //jRadioButtonTodos.setSelected(true);
        jCheckBoxTodos.setSelected(true);
        jCheckBoxAbertas.setSelected(true);
        jCheckBoxAndamento.setSelected(true);
        jCheckBoxAguardando.setSelected(true);
        jCheckBoxFechada.setSelected(true);
        jCheckBoxEntregue.setSelected(true);
        jRadioButtonTodos.setSelected(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        SistotalPUEntityManager = ConnectionFactory.getEntityManager();
        ordemServicoQuery = java.beans.Beans.isDesignTime() ? null : SistotalPUEntityManager.createQuery("SELECT o FROM OrdemServico o");
        //SituacaoOs sit1 = new SituacaoOs(1);
        //SituacaoOs sit2 = new SituacaoOs(2);
        //ordemServicoQuery = SistotalPUEntityManager.createNamedQuery("OrdemServico.findByNaoEntregue");
        //ordemServicoQuery.setParameter("situacao1", sit1);
        //ordemServicoQuery.setParameter("situacao2", sit2);
        ordemServicoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(ordemServicoQuery.getResultList());
        situacaoOsQuery = java.beans.Beans.isDesignTime() ? null : SistotalPUEntityManager.createQuery("SELECT s FROM SituacaoOs s");
        situacaoOsList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : situacaoOsQuery.getResultList();
        ordemServicoTableCellRenderer1 = new Renderizadores.OrdemServicoTableCellRenderer();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButtonOS = new javax.swing.JButton();
        jButtonClientes = new javax.swing.JButton();
        jButtonListaOS = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonVisualizar = new javax.swing.JButton();
        jComboBoxOsSelecionada = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jCheckBoxTodos = new javax.swing.JCheckBox();
        jCheckBoxAbertas = new javax.swing.JCheckBox();
        jCheckBoxAndamento = new javax.swing.JCheckBox();
        jCheckBoxAguardando = new javax.swing.JCheckBox();
        jCheckBoxFechada = new javax.swing.JCheckBox();
        jCheckBoxEntregue = new javax.swing.JCheckBox();
        jButtonFiltrar = new javax.swing.JButton();
        jComboBoxSituacaoOs = new javax.swing.JComboBox();
        jRadioButtonTodos = new javax.swing.JRadioButton();
        jRadioButtonPagos = new javax.swing.JRadioButton();
        jRadioButtonNaoPagos = new javax.swing.JRadioButton();
        jButtonImprimir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemClientes = new javax.swing.JMenuItem();
        jMenuItemEquipamento = new javax.swing.JMenuItem();
        jMenuItemOrdemServico = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jButtonOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/32x32/nova_os.png"))); // NOI18N
        jButtonOS.setText("Nova OS");
        jButtonOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonOS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOSActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOS);
        jButtonOS.setBounds(502, 23, 90, 70);

        jButtonClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/32x32/user.png"))); // NOI18N
        jButtonClientes.setText("Clientes");
        jButtonClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientesActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClientes);
        jButtonClientes.setBounds(282, 23, 90, 70);

        jButtonListaOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/32x32/2526_32x32.png"))); // NOI18N
        jButtonListaOS.setText("Lista OS");
        jButtonListaOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonListaOS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonListaOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListaOSActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonListaOS);
        jButtonListaOS.setBounds(393, 23, 90, 70);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, ordemServicoList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idordemServico}"));
        columnBinding.setColumnName("Código");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataAbertura}"));
        columnBinding.setColumnName("Data Abertura");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idcliente.nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idequipamento.descricao}"));
        columnBinding.setColumnName("Equipamento");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${marca}"));
        columnBinding.setColumnName("Marca");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idsituacaoOs.descricao}"));
        columnBinding.setColumnName("Situação");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataTermino}"));
        columnBinding.setColumnName("Data Entrega");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${valor}"));
        columnBinding.setColumnName("Valor");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${pago}"));
        columnBinding.setColumnName("Pago");
        columnBinding.setColumnClass(Boolean.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idtipoServico.descricao}"));
        columnBinding.setColumnName("Local");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable1MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(50);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(1).setMinWidth(85);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(85);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(85);
            jTable1.getColumnModel().getColumn(3).setMinWidth(100);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(5).setCellRenderer(ordemServicoTableCellRenderer1);
            jTable1.getColumnModel().getColumn(6).setMinWidth(85);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(85);
            jTable1.getColumnModel().getColumn(6).setMaxWidth(85);
            jTable1.getColumnModel().getColumn(7).setMinWidth(50);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(7).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(8).setMinWidth(50);
            jTable1.getColumnModel().getColumn(8).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(8).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(9).setMinWidth(80);
            jTable1.getColumnModel().getColumn(9).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(9).setMaxWidth(80);
            jTable1.getColumnModel().getColumn(9).setCellRenderer(ordemServicoTableCellRenderer1);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 180, 880, 342);

        jButtonVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/32x32/visualiza_os.png"))); // NOI18N
        jButtonVisualizar.setText("Visualiza");
        jButtonVisualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVisualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement!=null}"), jButtonVisualizar, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jButtonVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVisualizar);
        jButtonVisualizar.setBounds(620, 530, 90, 80);

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, ordemServicoList, jComboBoxOsSelecionada);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement}"), jComboBoxOsSelecionada, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jComboBoxOsSelecionada);
        jComboBoxOsSelecionada.setBounds(361, 535, 71, 20);

        jLabel1.setText("Ordens de Serviço");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 160, 623, 14);

        jCheckBoxTodos.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxTodos.setText("Todas");
        jCheckBoxTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTodosActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxTodos);
        jCheckBoxTodos.setBounds(900, 180, 140, 25);

        jCheckBoxAbertas.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxAbertas.setText("Abertas");
        jCheckBoxAbertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAbertasActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxAbertas);
        jCheckBoxAbertas.setBounds(900, 205, 140, 25);

        jCheckBoxAndamento.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxAndamento.setText("Andamento");
        jCheckBoxAndamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAndamentoActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxAndamento);
        jCheckBoxAndamento.setBounds(900, 230, 140, 25);

        jCheckBoxAguardando.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxAguardando.setText("Aguardando Cliente");
        jCheckBoxAguardando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAguardandoActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxAguardando);
        jCheckBoxAguardando.setBounds(900, 255, 140, 25);

        jCheckBoxFechada.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxFechada.setText("Fechada");
        jCheckBoxFechada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFechadaActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxFechada);
        jCheckBoxFechada.setBounds(900, 280, 140, 25);

        jCheckBoxEntregue.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxEntregue.setText("Entregue");
        jCheckBoxEntregue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEntregueActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxEntregue);
        jCheckBoxEntregue.setBounds(900, 305, 140, 25);

        jButtonFiltrar.setText("Atualizar");
        jButtonFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFiltrar);
        jButtonFiltrar.setBounds(700, 150, 90, 23);

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, situacaoOsList, jComboBoxSituacaoOs);
        bindingGroup.addBinding(jComboBoxBinding);

        jPanel1.add(jComboBoxSituacaoOs);
        jComboBoxSituacaoOs.setBounds(210, 540, 28, 20);

        jRadioButtonTodos.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButtonTodos);
        jRadioButtonTodos.setText("Pagos e não pagos");
        jRadioButtonTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTodosActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonTodos);
        jRadioButtonTodos.setBounds(900, 330, 140, 25);

        jRadioButtonPagos.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButtonPagos);
        jRadioButtonPagos.setText("Somente Pagos");
        jRadioButtonPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPagosActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonPagos);
        jRadioButtonPagos.setBounds(900, 355, 140, 25);

        jRadioButtonNaoPagos.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButtonNaoPagos);
        jRadioButtonNaoPagos.setText("Somente não Pagos");
        jRadioButtonNaoPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNaoPagosActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonNaoPagos);
        jRadioButtonNaoPagos.setBounds(900, 380, 140, 25);

        jButtonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/32x32/relatorio.png"))); // NOI18N
        jButtonImprimir.setText("Imprimir");
        jButtonImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement!=null}"), jButtonImprimir, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonImprimir);
        jButtonImprimir.setBounds(501, 530, 90, 80);

        jMenu1.setText("Cadastros");

        jMenuItemClientes.setText("Clientes");
        jMenuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClientesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemClientes);

        jMenuItemEquipamento.setText("Equipamento");
        jMenuItemEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEquipamentoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemEquipamento);

        jMenuItemOrdemServico.setText("Ordem de Serviço");
        jMenuItemOrdemServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOrdemServicoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemOrdemServico);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1059, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        setSize(new java.awt.Dimension(1075, 675));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientesActionPerformed
        TelaCadastroCliente tcc = new TelaCadastroCliente();
        tcc.setVisible(true);
    }//GEN-LAST:event_jButtonClientesActionPerformed

    private void jButtonOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOSActionPerformed
        TelaCadastroOrdemServico tosc = new TelaCadastroOrdemServico();
        tosc.setVisible(true);

    }//GEN-LAST:event_jButtonOSActionPerformed

    private void jButtonListaOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListaOSActionPerformed
        TelaListaOS tlo = new TelaListaOS();
        tlo.setVisible(true);
    }//GEN-LAST:event_jButtonListaOSActionPerformed

    private void jButtonVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarActionPerformed
        OrdemServico os = (OrdemServico) jComboBoxOsSelecionada.getSelectedItem();
        OrdemServicoController osController = new OrdemServicoController();
        try {
            os = osController.pesquisarPorId(os.getIdordemServico());
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        TelaCadastroOrdemServico tosc = new TelaCadastroOrdemServico(os);
        tosc.setVisible(true);
        System.gc();
    }//GEN-LAST:event_jButtonVisualizarActionPerformed

    private void jCheckBoxTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTodosActionPerformed
        if (jCheckBoxTodos.isSelected()) {
            jCheckBoxAbertas.setSelected(true);
            jCheckBoxAndamento.setSelected(true);
            jCheckBoxAguardando.setSelected(true);
            jCheckBoxFechada.setSelected(true);
            jCheckBoxEntregue.setSelected(true);
        } else {
            jCheckBoxAbertas.setSelected(false);
            jCheckBoxAndamento.setSelected(false);
            jCheckBoxAguardando.setSelected(false);
            jCheckBoxFechada.setSelected(false);
            jCheckBoxEntregue.setSelected(false);
        }

        this.jButtonFiltrarActionPerformed(evt);

    }//GEN-LAST:event_jCheckBoxTodosActionPerformed

    private void jButtonFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltrarActionPerformed
        if (!jCheckBoxAbertas.isSelected()
                && !jCheckBoxAndamento.isSelected()
                && !jCheckBoxAguardando.isSelected()
                && !jCheckBoxFechada.isSelected()
                && !jCheckBoxEntregue.isSelected()) {
            //JOptionPane.showMessageDialog(rootPane, "Selecione algum tipo de situação de Ordem de Serviço");
        } else {

            String auxSql = "";
            String auxSqlPago = "";
            if (jCheckBoxAbertas.isSelected()) {
                auxSql = auxSql + "1";
            }
            if (jCheckBoxAndamento.isSelected()) {
                auxSql = auxSql + "2";
            }
            if (jCheckBoxFechada.isSelected()) {
                auxSql = auxSql + "3";
            }
            if (jCheckBoxAguardando.isSelected()) {
                auxSql = auxSql + "4";
            }
            if (jCheckBoxEntregue.isSelected()) {
                auxSql = auxSql + "5";
            }

            if (jRadioButtonNaoPagos.isSelected()) {
                auxSqlPago = "0";
            } else {
                if (jRadioButtonPagos.isSelected()) {
                    auxSqlPago = "1";
                } else {
                    auxSqlPago = "0,1";
                }

            }

            char[] teste = auxSql.toCharArray();
            auxSql = "";
            for (int i = 0; i < teste.length; i++) {

                auxSql = auxSql + teste[i];
                int j = i;
                if (j < (teste.length - 1)) {
                    auxSql = auxSql + ",";
                }
            }

//            
            ordemServicoQuery = SistotalPUEntityManager.createNativeQuery("Select * from ordem_servico where idsituacao_os in (" + auxSql + ") and pago in (" + auxSqlPago + ")", OrdemServico.class);
            ordemServicoList.clear();
            List<OrdemServico> temp = ordemServicoQuery.getResultList();
            ordemServicoList.addAll(temp);
//            for (int i = 0; i < ordemServicoList.size(); i++) {
//                SistotalPUEntityManager.refresh(ordemServicoList.get(i));
//                SistotalPUEntityManager.refresh(ordemServicoList.get(i).getIdcliente());
//            }

        }
    }//GEN-LAST:event_jButtonFiltrarActionPerformed

    private void jCheckBoxAbertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAbertasActionPerformed
        if (!jCheckBoxAbertas.isSelected()) {
            jCheckBoxTodos.setSelected(false);
        }
        this.jButtonFiltrarActionPerformed(evt);
    }//GEN-LAST:event_jCheckBoxAbertasActionPerformed

    private void jCheckBoxAndamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAndamentoActionPerformed
        if (!jCheckBoxAndamento.isSelected()) {
            jCheckBoxTodos.setSelected(false);
        }
        this.jButtonFiltrarActionPerformed(evt);
    }//GEN-LAST:event_jCheckBoxAndamentoActionPerformed

    private void jCheckBoxAguardandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAguardandoActionPerformed
        if (!jCheckBoxAguardando.isSelected()) {
            jCheckBoxTodos.setSelected(false);
        }
        this.jButtonFiltrarActionPerformed(evt);
    }//GEN-LAST:event_jCheckBoxAguardandoActionPerformed

    private void jCheckBoxFechadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFechadaActionPerformed
        if (!jCheckBoxFechada.isSelected()) {
            jCheckBoxTodos.setSelected(false);
        }
        this.jButtonFiltrarActionPerformed(evt);
    }//GEN-LAST:event_jCheckBoxFechadaActionPerformed

    private void jCheckBoxEntregueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEntregueActionPerformed
        if (!jCheckBoxEntregue.isSelected()) {
            jCheckBoxTodos.setSelected(false);
        }
        this.jButtonFiltrarActionPerformed(evt);
    }//GEN-LAST:event_jCheckBoxEntregueActionPerformed

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered


    }//GEN-LAST:event_jTable1MouseEntered


    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() > 1) {
            OrdemServico os = (OrdemServico) jComboBoxOsSelecionada.getSelectedItem();
            OrdemServicoController osController = new OrdemServicoController();
            try {
                os = osController.pesquisarPorId(os.getIdordemServico());
            } catch (SQLException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
            TelaCadastroOrdemServico tosc = new TelaCadastroOrdemServico(os);
            tosc.setVisible(true);
            System.gc();
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jRadioButtonTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTodosActionPerformed
        this.jButtonFiltrarActionPerformed(evt);
    }//GEN-LAST:event_jRadioButtonTodosActionPerformed

    private void jRadioButtonPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPagosActionPerformed
        this.jButtonFiltrarActionPerformed(evt);
    }//GEN-LAST:event_jRadioButtonPagosActionPerformed

    private void jRadioButtonNaoPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNaoPagosActionPerformed
        this.jButtonFiltrarActionPerformed(evt);
    }//GEN-LAST:event_jRadioButtonNaoPagosActionPerformed

    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
        OrdemServico os = (OrdemServico) jComboBoxOsSelecionada.getSelectedItem();
        String sistemaOperacional = os.getSistemaOperacional();
        String antiVirus = os.getAntivirus();
        String office = os.getOffice();
        ExecutaRelatorio er = new ExecutaRelatorio();
        er.abrirRelatorioOS(os, sistemaOperacional, antiVirus, office);
        this.toBack();

    }//GEN-LAST:event_jButtonImprimirActionPerformed

    private void jMenuItemEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEquipamentoActionPerformed
        TelaListaEquipamento tce = new TelaListaEquipamento();
        tce.setVisible(true);
    }//GEN-LAST:event_jMenuItemEquipamentoActionPerformed

    private void jMenuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClientesActionPerformed
        TelaCadastroCliente tcc = new TelaCadastroCliente();
        tcc.setVisible(true);
    }//GEN-LAST:event_jMenuItemClientesActionPerformed

    private void jMenuItemOrdemServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOrdemServicoActionPerformed
        TelaListaOS tlo = new TelaListaOS();
        tlo.setVisible(true);
    }//GEN-LAST:event_jMenuItemOrdemServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                System.out.println(info.getName());
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    System.out.println(info.getName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager SistotalPUEntityManager;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonClientes;
    private javax.swing.JButton jButtonFiltrar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonListaOS;
    private javax.swing.JButton jButtonOS;
    private javax.swing.JButton jButtonVisualizar;
    private javax.swing.JCheckBox jCheckBoxAbertas;
    private javax.swing.JCheckBox jCheckBoxAguardando;
    private javax.swing.JCheckBox jCheckBoxAndamento;
    private javax.swing.JCheckBox jCheckBoxEntregue;
    private javax.swing.JCheckBox jCheckBoxFechada;
    private javax.swing.JCheckBox jCheckBoxTodos;
    private javax.swing.JComboBox jComboBoxOsSelecionada;
    private javax.swing.JComboBox jComboBoxSituacaoOs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemClientes;
    private javax.swing.JMenuItem jMenuItemEquipamento;
    private javax.swing.JMenuItem jMenuItemOrdemServico;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonNaoPagos;
    private javax.swing.JRadioButton jRadioButtonPagos;
    private javax.swing.JRadioButton jRadioButtonTodos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.util.List<model.OrdemServico> ordemServicoList;
    private javax.persistence.Query ordemServicoQuery;
    private Renderizadores.OrdemServicoTableCellRenderer ordemServicoTableCellRenderer1;
    private java.util.List<model.SituacaoOs> situacaoOsList;
    private javax.persistence.Query situacaoOsQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
